<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\lmsapi.modellibrary\LMSApi.ModelLibrary.csproj" />
    <ProjectReference Include="..\LMSApi.DALLibrary\LMSApi.DALLibrary.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="6.31.0" />
  </ItemGroup>

</Project>
